#!/bin/bash
set -euo pipefail

width=$(tput cols)
height=$(($(tput lines) - 1)) # Because bat has prompt line in the bottom and two grid lines
input_file=""

while getopts ":f:" opt; do
  case $opt in
    f)
      input_file="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND -1))

[ -n "$input_file" ] || { echo "Error: File is required (-f)"; exit 1; }
[ -r "$input_file" ] || { echo "Error: Can't read '$input_file'"; exit 1; }

rich -w "$width" "$input_file" | sponge "$input_file"

input_file_lines=$(wc -l < "$input_file")
if [[ "$input_file_lines" -lt "$height" ]]; then
	yes '' | head -n $(("$height" - "$input_file_lines")) >> "$input_file"
fi
